# Generated by Django 3.2.10 on 2023-10-05 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20231004_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='use_case',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
